#!/bin/bash

# Check if .env file exists
if [ -f ../.env ]; then
    # Load environment variables from .env file (parent directory)
    export $(grep -v '^#' ../.env | xargs)
else
    echo "Error: ../.env file not found"
    exit 1
fi

# Check if PUBLIC_IP variable is set
if [ -z "$PUBLIC_IP" ]; then
    echo "Error: PUBLIC_IP variable not found in .env"
    exit 1
fi

echo "Updating config.js with public IP: $PUBLIC_IP"

# Write new content to config.js
cat > config.js <<JSKEY
const APP_CONFIG = {
    // Automatically generated by generate_config.sh (Source: .env)
    API_URL: 'http://$PUBLIC_IP:8080/v1/internal/stats',
    API_KEY: 'change-me'
};
JSKEY

echo "Success! config.js has been updated."
