[kafka_cluster]
node1 ansible_host=34.87.53.240 node_id=1
node2 ansible_host=34.142.148.5 node_id=2
node3 ansible_host=34.176.109.227 node_id=3

[kafka_cluster:vars]
ansible_user=root
ansible_become=yes
ansible_ssh_private_key_file=~/.ssh/bigdata_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes'
